feat: ensure TAG set in deploy script

diff --git a/ansible/playbooks/roles/k3s/deploy/templates/deploy.sh.j2 b/ansible/playbooks/roles/k3s/deploy/templates/deploy.sh.j2
--- a/ansible/playbooks/roles/k3s/deploy/templates/deploy.sh.j2
+++ b/ansible/playbooks/roles/k3s/deploy/templates/deploy.sh.j2
@@ -2,6 +2,11 @@
 
 set -o errexit
 
+if [ -z "$TAG" ]; then
+  echo "ERROR: TAG must be set to the image tag to deploy"
+  exit 1
+fi
+
 export KUBECONFIG="{{ kubeconfig }}"
 
 export IMAGE="{{ docker_image.split(":")[0] }}:$TAG"
