refactor: deployment fixes

diff --git a/ansible/playbooks/roles/k3s/deploy/templates/deploy.sh.j2 b/ansible/playbooks/roles/k3s/deploy/templates/deploy.sh.j2
--- a/ansible/playbooks/roles/k3s/deploy/templates/deploy.sh.j2
+++ b/ansible/playbooks/roles/k3s/deploy/templates/deploy.sh.j2
@@ -46,46 +46,24 @@ EOF
 
 echo "$release_job_yaml" | kubectl apply -f - -n default
 
+# Wait for the release job to complete: 60 seconds timeout
+kubectl wait --for=condition=complete job/$release_job_name --timeout=60s || true
+
 release_pod_name=$(kubectl get pods -l job-name=$release_job_name -o jsonpath='{.items[0].metadata.name}')
 release_pod_status=$(kubectl get pod $release_pod_name -o jsonpath='{.status.phase}')
 
-delete_release_job() {
-    kubectl logs $release_pod_name
-    kubectl delete pod $release_pod_name
-    kubectl delete job $release_job_name
-}
+# Display logs of the release job if available
+if kubectl get pod $release_pod_name &>/dev/null; then
+  kubectl logs $release_pod_name
+fi
 
-max_retries=30
-count=0
+# Delete the job
+kubectl delete job $release_job_name
 
-# NOTE: "kubectl wait" does not work because we can't set a "success OR failure" condition
-
-while true; do
-    # Get the job status (complete or failed)
-    success_status=$(kubectl get job $release_job_name -o jsonpath='{.status.succeeded}')
-    failed_status=$(kubectl get job $release_job_name -o jsonpath='{.status.failed}')
-
-    if [[ "$success_status" == "1" ]]; then
-        echo "Job completed successfully."
-        delete_release_job
-        break
-    fi
-
-    if [[ "$failed_status" == "1" ]]; then
-        echo "Job failed exiting ..."
-        delete_release_job
-        exit 1
-    fi
-
-    if [[ $count -ge $max_retries ]]; then
-        echo "Timed out waiting for job to complete"
-        delete_release_job
-        exit 1
-    fi
-
-    sleep 5
-    count=$((count + 1))
-done
+if [ $release_pod_status != 'Succeeded' ]; then
+  echo "ERROR: Release job failed with status $release_pod_status"
+  exit 1
+fi
 
 echo "Deploying application..."
 
